object Form_Principal: TForm_Principal
  Left = 0
  Top = 0
  BorderIcons = [biSystemMenu, biMinimize]
  BorderStyle = bsSingle
  BorderWidth = 2
  Caption = 'Calculadora'
  ClientHeight = 344
  ClientWidth = 307
  Color = 10485760
  DefaultMonitor = dmPrimary
  Font.Charset = DEFAULT_CHARSET
  Font.Color = clWindowText
  Font.Height = -11
  Font.Name = 'Tahoma'
  Font.Style = []
  OldCreateOrder = False
  Position = poScreenCenter
  PixelsPerInch = 96
  TextHeight = 13
  object P_central: TPanel
    AlignWithMargins = True
    Left = 0
    Top = -32
    Width = 363
    Height = 395
    BevelOuter = bvNone
    BorderWidth = 20
    BorderStyle = bsSingle
    Color = clBlack
    ParentBackground = False
    TabOrder = 0
    object P_tela: TPanel
      Left = -1
      Top = 14
      Width = 327
      Height = 99
      Color = clGradientInactiveCaption
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clHotLight
      Font.Height = -11
      Font.Name = 'Tahoma'
      Font.Style = []
      ParentBackground = False
      ParentFont = False
      TabOrder = 0
      object P_barra3: TPanel
        Left = 0
        Top = 0
        Width = 2
        Height = 83
        Color = 10485760
        ParentBackground = False
        TabOrder = 0
      end
      object P_barra2: TPanel
        Left = 328
        Top = 0
        Width = 3
        Height = 83
        Color = 10485760
        ParentBackground = False
        TabOrder = 1
      end
      object P_barra: TPanel
        Left = 0
        Top = 95
        Width = 322
        Height = 4
        Color = 10485760
        ParentBackground = False
        TabOrder = 2
      end
      object Button17: TButton
        Left = 264
        Top = 72
        Width = 42
        Height = 17
        Caption = '<--'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clHotLight
        Font.Height = -19
        Font.Name = 'Arial Black'
        Font.Style = [fsBold, fsItalic]
        ParentFont = False
        TabOrder = 3
      end
      object Edit1: TEdit
        Left = 8
        Top = 60
        Width = 250
        Height = 35
        Alignment = taRightJustify
        BorderStyle = bsNone
        CharCase = ecUpperCase
        Color = clGradientInactiveCaption
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clBlack
        Font.Height = -27
        Font.Name = 'Arial Black'
        Font.Style = []
        Font.Quality = fqClearTypeNatural
        ParentFont = False
        TabOrder = 4
        Text = '0123456789'
      end
    end
    object Button1: TButton
      Left = -1
      Top = 119
      Width = 74
      Height = 58
      Caption = '7'
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWindowText
      Font.Height = -20
      Font.Name = 'Tahoma'
      Font.Style = []
      ParentFont = False
      TabOrder = 1
    end
    object Button2: TButton
      Left = 79
      Top = 119
      Width = 74
      Height = 58
      Caption = '8'
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWindowText
      Font.Height = -20
      Font.Name = 'Tahoma'
      Font.Style = []
      ParentFont = False
      TabOrder = 2
    end
    object Button3: TButton
      Left = 159
      Top = 119
      Width = 70
      Height = 58
      Caption = '9'
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWindowText
      Font.Height = -20
      Font.Name = 'Tahoma'
      Font.Style = []
      ParentFont = False
      TabOrder = 3
    end
    object Button4: TButton
      Left = 235
      Top = 119
      Width = 70
      Height = 58
      Caption = #247
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWindowText
      Font.Height = -20
      Font.Name = 'Tahoma'
      Font.Style = []
      ParentFont = False
      TabOrder = 4
    end
    object Button5: TButton
      Left = 235
      Top = 183
      Width = 70
      Height = 58
      Caption = 'x'
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWindowText
      Font.Height = -20
      Font.Name = 'Tahoma'
      Font.Style = []
      ParentFont = False
      TabOrder = 5
    end
    object Button6: TButton
      Left = 159
      Top = 183
      Width = 70
      Height = 58
      Caption = '6'
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWindowText
      Font.Height = -20
      Font.Name = 'Tahoma'
      Font.Style = []
      ParentFont = False
      TabOrder = 6
    end
    object Button7: TButton
      Left = 79
      Top = 183
      Width = 74
      Height = 58
      Caption = '5'
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWindowText
      Font.Height = -20
      Font.Name = 'Tahoma'
      Font.Style = []
      ParentFont = False
      TabOrder = 7
    end
    object Button8: TButton
      Left = -1
      Top = 183
      Width = 74
      Height = 58
      Caption = '4'
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWindowText
      Font.Height = -20
      Font.Name = 'Tahoma'
      Font.Style = []
      ParentFont = False
      TabOrder = 8
    end
    object Button9: TButton
      Left = 235
      Top = 247
      Width = 70
      Height = 58
      Caption = '-'
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWindowText
      Font.Height = -20
      Font.Name = 'Tahoma'
      Font.Style = []
      ParentFont = False
      TabOrder = 9
    end
    object Button10: TButton
      Left = 159
      Top = 247
      Width = 70
      Height = 58
      Caption = '3'
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWindowText
      Font.Height = -20
      Font.Name = 'Tahoma'
      Font.Style = []
      ParentFont = False
      TabOrder = 10
    end
    object Button11: TButton
      Left = 79
      Top = 247
      Width = 74
      Height = 58
      Caption = '2'
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWindowText
      Font.Height = -20
      Font.Name = 'Tahoma'
      Font.Style = []
      ParentFont = False
      TabOrder = 11
    end
    object Button12: TButton
      Left = -1
      Top = 247
      Width = 74
      Height = 58
      Caption = '1'
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWindowText
      Font.Height = -20
      Font.Name = 'Tahoma'
      Font.Style = []
      ParentFont = False
      TabOrder = 12
    end
    object Button13: TButton
      Left = 235
      Top = 311
      Width = 70
      Height = 58
      Caption = '+'
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWindowText
      Font.Height = -20
      Font.Name = 'Tahoma'
      Font.Style = []
      ParentFont = False
      TabOrder = 13
    end
    object Button14: TButton
      Left = 159
      Top = 311
      Width = 70
      Height = 58
      Caption = '='
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWindowText
      Font.Height = -20
      Font.Name = 'Tahoma'
      Font.Style = []
      ParentFont = False
      TabOrder = 14
    end
    object Button15: TButton
      Left = 79
      Top = 311
      Width = 74
      Height = 58
      Caption = ','
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWindowText
      Font.Height = -20
      Font.Name = 'Tahoma'
      Font.Style = []
      ParentFont = False
      TabOrder = 15
    end
    object Button16: TButton
      Left = -1
      Top = 311
      Width = 74
      Height = 58
      Caption = '0'
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWindowText
      Font.Height = -20
      Font.Name = 'Tahoma'
      Font.Style = []
      ParentFont = False
      TabOrder = 16
    end
  end
end
